pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@4
  inputs:
    azureSubscription: 'Planet'
    ScriptType: 'FilePath'
    ScriptPath: 'ActionRole.ps1'
    ScriptArguments:
    azurePowerShellVersion: 'LatestVersion'

  