pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
  - task: AzurePowerShell@4
    inputs:
      azureSubscription: 'MAC.WEST.DEVOPS(8ee2aaf4-8329-4aa2-afa2-21cda345f7d4)'
      ScriptType: 'FilePath'
      ScriptPath: 'NewRoleCreation.ps1'
      azurePowerShellVersion: 'LatestVersion'