pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@4
  inputs:
    azureSubscription: $(Subscription)
    ScriptPath: 'https://kgreen0633@dev.azure.com/kgreen0633/SecurityOperations/_git/SecurityOperations/NewRoleCreation.ps1'
    ScriptArguments: 
    azurePowerShellVersion: LatestVersion