pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@4
  inputs:
    azureSubscription: $(Subscription)
    ScriptPath: 'SecurityOperations/NewRoleCreation.ps1'
    ScriptArguments: -ResourceGroupName 'RBACPipeline' -ResourceGroupLocation 'West US'
    azurePowerShellVersion: LatestVersion

  