pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps
steps:
- task: AzurePowerShell@4
  inputs:
    azureSubscription: 'Contoso_rbac'
    ScriptType: 'FilePath'
    ScriptPath: 'ActionRole.ps1'
    ScriptArguments:
    azurePowerShellVersion: 'LatestVersion'

  