pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@4
  inputs:
    azureSubscription: $(Subscription)
    Script: New-AzRoleDefinition
    ScriptArguments: -InputFile "SecurityOperations/RBAC_AppDev.JSON"
    azurePowerShellVersion: LatestVersion

  